### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Jeeses313** [tulma95/ostoslistaSovellus#1]
6.4.2019 klo. 12.24 

Koodi on hyvin selkeää ja luokat, metodit ja muuttujat on nimetty niin, että niiden toiminnasta saa jonkinlaisen kuvan. 

Myös dokumentaatio on selkeä ja on ohjelman mukainen, mutta sovellus ei vielä toteuta kaikkia käyttötapaksia:

- Käyttäjätilin poisto

- Ryhmästä poistuminen

- Ryhmän postaminen

Ulkonäössä ainoa huomautettava seikka on se, että Herokussa ryhmän tuotteiden listauksessa tuotteen nimi ja määrä ovat kiinni toisisaan, mutta paikallisessa versiossa kuitenkin hyvin erillään.

Muita ohjelman toimintaan liityviä asioita:

- Tuotteiden määrä voi mennä negatiiviseksi. Tämän voisi helposti vältää lisämällä if-lause vähennys metodiin.

- Tuotteiden suurien määrien lisääminen ja vähentäminen ostoslistassa on hidasta/raskasta. Jos jostain syystä haluaisi lisätä ostoslistaan 1000 ilmapalloa juhlia varten, menisi paljon aikaa tai voisi saada jännetuppitulehduksen.

- Käyttäjien, ryhmien ja tuotteiden nimistä ei validoida, onko niitä jo olemassa tai jo listassa. Varsinkin käyttäjissä tämä on ongelma, koska esimerkiksi voi tehdä kaksi samannimistä käyttäjää, jolloin on mahdotonta ryhmään lisätessä tietää kumpaa on haluttu käyttäjä. Tämän voisi välttää esimerkiksi tekemällä validoinnin, jossa tehdään kyselyn, joka hakee käyttäjän nimen perusteella, ja sitten katsotaan, onko käyttäjä olemassa, eli User vai NULL, esim. `if(kyselyn_tulos is None):`.

-  Käyttäjiin liitetään nimi, tilin luontipäivä ja muokkauspäivä, vaikka niillä ei tehdä mitään eikä niitä ole dokumentaatiossa, vaikka nimeä pyydetäänkin rekisteröityessä. 

- Kun käyttäjiä lisätään ryhmään, listataan mahdollisissa lisättävissä lisääjä itse ja ryhmässä jo olevat käyttäjät. Tämän voisi halutessa välttää tekemällä kysely, jossa on esim. `WHERE Account.id NOT IN (*sopiva alikysely*)`. 

- Rekisteröityminen voisi ehkä myös kirjautua samalla, niin ei tarvisisi kirjoittaa käyttäjänimeä toista ja salasanaa kolmatta kertaa.

**Comment by tulma95** [comment]
Kiitos kommentista. Puutteet tullaan korjaamaan viimeistään lopulliseen versioon.
