### ISSUE TITLE
Koodikatselmointi II

### ISSUE THREAD

**Issue by kordaniel** [tulma95/ostoslistaSovellus#2]
# Tsoha katselmointi II
Testasin projektia herokussa 28.4 kl ~14:00. Koodin kävin lävitse vasta 29.4 kl 1930. Näiden aikakohtien välissä repositorioon on tullut päivityksiä, joten osa kommenteistani perustuu jo vanhaan versioon. Heti alkuun piste siitä että projekti näyttää edistyvän koko ajan! :)  

### Dokumentaatio
 +Selkeät asennusohjeet lokaaliin asennukseen
 -Mutta herokun asennusohjeet puuttuvat kokonaan
 +Tietokantakaavio löytyy
 -SQL CREATE -lauseet puuttuvat
 +Käyttötapaukset erittäin hienosti tehty sekä SQL-kyselyt on myös listattu :)
 
### Huomioita sovelluksen testaamisesta:
+ Ryhmän luonti onnistuu herokussa
 + listaa ryhmän jäsenet
 + ryhmään voi lisätä käyttäjiä
   
Ryhmän luoja voi poistaa itsensä ryhmästä, jonka jälkeen ryhmää ei voi poistaa?
 - jollei softa automaattisesti poista ryhmää kun viimeinen henkilö poistuu ryhmästä (en testannut)?
 
+ Käyttäjä voi luoda ryhmän
 + toinen voi liittyä siihen
 + ryhmän luoja voi poistua ryhmästä
 +- käyttäjä voi luoda toisen samannimisen ryhmän tämän jälkeen, joilla eri sisällöt/käyttäjät

 + jos ei kirjautunut käyttäjä yrittää avata ryhmien listauksen (menemällä osoitteeseen https://pro-ostoslista-sovellus.herokuapp.com/groups/) niin sovellus ohjaa kirjautumisruutuun
 - mutta ryhmiä voi silti tarkastella (https://pro-ostoslista-sovellus.herokuapp.com/groups/<ryhmä_n>).
  - Tällöin sovellus myös näyttää Add product napin, joka ei kuitenkaan anna lisätä ryhmään tuotteita vaan ohjaa kirjautumisruutuun.
  - ei kirjautunut käyttäjä voi myös nähdä ketkä käyttäjät kuuluvat ryhmään (https://pro-ostoslista-sovellus.herokuapp.com/groups/<ryhmä_n>/info?). Tämähän ei ole huono asia, jos sovelluksen on tarkoitus toimia näin. Näille sivuille ei kuitenkaan ole linkkejä missään, niin oletan että ne on tarkoitus piilottaa? Samoin samalla sivulla ei kirjautuneelle käyttäjälle näytetään Leave group-nappi, jonka painaminen tuottaa Internal server error-viestin.
 
Rekisteröityminen:
 + validointi toimii
 + rekisteröinti toimii
  - mutta ei loggaa sisään automaattisesti
 + tilin poisto onnistuu
 -profiilisivun (https://pro-ostoslista-sovellus.herokuapp.com/auth/info) avaaminen onnistuu, vaikka käyttäjä ei olisi kirjautunut sekä näyttää myös delete account napin. Nappulaa painamalla sovellus näyttää Internal server error-viestin. Tämä olisi varmaan hyvä muuttaa niin, että näytetään jonkunlainen viesti "not logged in" tai yksinkertaisesti ei päästetä käyttäjää sivulle?

+ Achecker ei löydä virheitä, testattu usealla eri alasivulla!

### Koodi
Yleisesti ottaen koodi on mielestäni siistiä ja niin luokat kuin metoditkin on nimetty järkevästi. Samoin muuttujien kohdalla. Jos oikein suurenuslasilla etsii, niin groups_index()-funktiossa on yksi hieman hassusti nimetty muuttuja, query. Toisin sanoen, niin koodia on miellyttävän helppoa lukea ja ymmärtää ohjelman toiminta! :)

Pari kehitysehdotusta tuli kuitenkin mieleeni:

 -Modeleissa voisi varmaan ottaa käyttöön materiaalissakin esitetty abstrakti Base-luokka, koska melkein kaikissa modeleissa toistuu kentät id, date_created, date_modified sekä name, tämä selkeyttäisi koodia vielä entisestään.
 
 -User-modelissa on kenttä password, johon mahtuu 144 merkkiä pitkä salasana, formissa olet kuitenkin rajoittanut salasanan pituuden enintään 12 merkkiin. Samoin ainakin Groupissa pituudet eivät täsmää modelin ja formin välillä.  

 -Myös tietokannan puolella account-taulun name voi olla 144 merkkiä kun Group-taulun groupCreator voi olla vain 50 merkkiä pitkä. groupCreator-kenttää käytetään varmaan merkitsemään kuka on luonut ryhmän? Tiedon tallentaminen pelkkänä stringinä voi käsittääkseni olla monella tapaa ongelmallista, esimerkiksi jos käyttäjä päättää vaihtaa nimensä, niin silloin varmaan on tarkoitus että nimi vaihtuu myös ryhmässä. Nyt sinun tai koodisi pitäisi itse päivittää nimi myös ryhmään. Parempi tapa olisi ehkä käyttää sqlalchemyn one to one yhteyttä, jolloin asia hoituisi automaagisesti. Tietysti vielä tällä ei ole väliä, kun käyttäjätietoja ei pysty muokkaamaan mutta noin yleisellä tasolla  

 -account_info()-funktio: Poistat ensin rivin liitostaulusta "manuaalisesti", jonka jälkeen poistat käyttäjän sqlalchemyn avulla. Tämä ei minun silmään näytä niin siistiltä, varmaan jos kaikki määritelmät on tehty oikein, niin tuosta manuaalisesta poistamisesta pääsisi eroon? Ehkä tämä on tässä vain kurssin arvostelun takia, en ole vielä niin tarkasti tutustunut arvosteluperiaatteisiin :)
 
Kaiken kaikkiaan mielenkiintoinen projekti, jolle itsellenikin voisi ihan oikeasti olla arjessa käyttöä! Onnea loppurutistukseen :)

**Comment by tulma95** [comment]
Kiitos erittäin kattavasta koodikatselmoinnista! Yritin saada rivien poistamisen liitostaulusta toimimaan automaagisesti "cascade = delete_orphan"-tavalla mutta en saanut sitä toimimaan, tästä syystä manuaalinen sql-kysely...
